(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.superagent=f()}})(function(){var define,module,exports;return(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){function Agent(){this._defaults=[];}
["use","on","once","set","query","type","accept","auth","withCredentials","sortQuery","retry","ok","redirects","timeout","buffer","serialize","parse","ca","key","pfx","cert"].forEach(function(fn){Agent.prototype[fn]=function(){this._defaults.push({fn:fn,arguments:arguments});return this;}});Agent.prototype._setDefaults=function(req){this._defaults.forEach(function(def){req[def.fn].apply(req,def.arguments);});};module.exports=Agent;},{}],2:[function(require,module,exports){'use strict';function isObject(obj){return null!==obj&&'object'===typeof obj;}
module.exports=isObject;},{}],3:[function(require,module,exports){'use strict';var isObject=require('./is-object');module.exports=RequestBase;function RequestBase(obj){if(obj)return mixin(obj);}
function mixin(obj){for(var key in RequestBase.prototype){obj[key]=RequestBase.prototype[key];}
return obj;}
RequestBase.prototype.clearTimeout=function _clearTimeout(){clearTimeout(this._timer);clearTimeout(this._responseTimeoutTimer);delete this._timer;delete this._responseTimeoutTimer;return this;};RequestBase.prototype.parse=function parse(fn){this._parser=fn;return this;};RequestBase.prototype.responseType=function(val){this._responseType=val;return this;};RequestBase.prototype.serialize=function serialize(fn){this._serializer=fn;return this;};RequestBase.prototype.timeout=function timeout(options){if(!options||'object'!==typeof options){this._timeout=options;this._responseTimeout=0;return this;}
for(var option in options){switch(option){case 'deadline':this._timeout=options.deadline;break;case 'response':this._responseTimeout=options.response;break;default:console.warn("Unknown timeout option",option);}}
return this;};RequestBase.prototype.retry=function retry(count,fn){if(arguments.length===0||count===true)count=1;if(count<=0)count=0;this._maxRetries=count;this._retries=0;this._retryCallback=fn;return this;};var ERROR_CODES=['ECONNRESET','ETIMEDOUT','EADDRINFO','ESOCKETTIMEDOUT'];RequestBase.prototype._shouldRetry=function(err,res){if(!this._maxRetries||this._retries++>=this._maxRetries){return false;}
if(this._retryCallback){try{var override=this._retryCallback(err,res);if(override===true)return true;if(override===false)return false;}catch(e){console.error(e);}}
if(res&&res.status&&res.status>=500&&res.status!=501)return true;if(err){if(err.code&&~ERROR_CODES.indexOf(err.code))return true;if(err.timeout&&err.code=='ECONNABORTED')return true;if(err.crossDomain)return true;}
return false;};RequestBase.prototype._retry=function(){this.clearTimeout();if(this.req){this.req=null;this.req=this.request();}
this._aborted=false;this.timedout=false;return this._end();};RequestBase.prototype.then=function then(resolve,reject){if(!this._fullfilledPromise){var self=this;if(this._endCalled){console.warn("Warning: superagent request was sent twice, because both .end() and .then() were called. Never call .end() if you use promises");}
this._fullfilledPromise=new Promise(function(innerResolve,innerReject){self.end(function(err,res){if(err)innerReject(err);else innerResolve(res);});});}
return this._fullfilledPromise.then(resolve,reject);};RequestBase.prototype['catch']=function(cb){return this.then(undefined,cb);};RequestBase.prototype.use=function use(fn){fn(this);return this;};RequestBase.prototype.ok=function(cb){if('function'!==typeof cb)throw Error("Callback required");this._okCallback=cb;return this;};RequestBase.prototype._isResponseOK=function(res){if(!res){return false;}
if(this._okCallback){return this._okCallback(res);}
return res.status>=200&&res.status<300;};RequestBase.prototype.get=function(field){return this._header[field.toLowerCase()];};RequestBase.prototype.getHeader=RequestBase.prototype.get;RequestBase.prototype.set=function(field,val){if(isObject(field)){for(var key in field){this.set(key,field[key]);}
return this;}
this._header[field.toLowerCase()]=val;this.header[field]=val;return this;};RequestBase.prototype.unset=function(field){delete this._header[field.toLowerCase()];delete this.header[field];return this;};RequestBase.prototype.field=function(name,val){if(null===name||undefined===name){throw new Error('.field(name, val) name can not be empty');}
if(this._data){console.error(".field() can't be used if .send() is used. Please use only .send() or only .field() & .attach()");}
if(isObject(name)){for(var key in name){this.field(key,name[key]);}
return this;}
if(Array.isArray(val)){for(var i in val){this.field(name,val[i]);}
return this;}
if(null===val||undefined===val){throw new Error('.field(name, val) val can not be empty');}
if('boolean'===typeof val){val=''+val;}
this._getFormData().append(name,val);return this;};RequestBase.prototype.abort=function(){if(this._aborted){return this;}
this._aborted=true;this.xhr&&this.xhr.abort();this.req&&this.req.abort();this.clearTimeout();this.emit('abort');return this;};RequestBase.prototype._auth=function(user,pass,options,base64Encoder){switch(options.type){case 'basic':this.set('Authorization','Basic '+base64Encoder(user+':'+pass));break;case 'auto':this.username=user;this.password=pass;break;case 'bearer':this.set('Authorization','Bearer '+user);break;}
return this;};RequestBase.prototype.withCredentials=function(on){if(on==undefined)on=true;this._withCredentials=on;return this;};RequestBase.prototype.redirects=function(n){this._maxRedirects=n;return this;};RequestBase.prototype.maxResponseSize=function(n){if('number'!==typeof n){throw TypeError("Invalid argument");}
this._maxResponseSize=n;return this;};RequestBase.prototype.toJSON=function(){return{method:this.method,url:this.url,data:this._data,headers:this._header,};};RequestBase.prototype.send=function(data){var isObj=isObject(data);var type=this._header['content-type'];if(this._formData){console.error(".send() can't be used if .attach() or .field() is used. Please use only .send() or only .field() & .attach()");}
if(isObj&&!this._data){if(Array.isArray(data)){this._data=[];}else if(!this._isHost(data)){this._data={};}}else if(data&&this._data&&this._isHost(this._data)){throw Error("Can't merge these send calls");}
if(isObj&&isObject(this._data)){for(var key in data){this._data[key]=data[key];}}else if('string'==typeof data){if(!type)this.type('form');type=this._header['content-type'];if('application/x-www-form-urlencoded'==type){this._data=this._data?this._data+'&'+data:data;}else{this._data=(this._data||'')+data;}}else{this._data=data;}
if(!isObj||this._isHost(data)){return this;}
if(!type)this.type('json');return this;};RequestBase.prototype.sortQuery=function(sort){this._sort=typeof sort==='undefined'?true:sort;return this;};RequestBase.prototype._finalizeQueryString=function(){var query=this._query.join('&');if(query){this.url+=(this.url.indexOf('?')>=0?'&':'?')+query;}
this._query.length=0;if(this._sort){var index=this.url.indexOf('?');if(index>=0){var queryArr=this.url.substring(index+1).split('&');if('function'===typeof this._sort){queryArr.sort(this._sort);}else{queryArr.sort();}
this.url=this.url.substring(0,index)+'?'+queryArr.join('&');}}};RequestBase.prototype._appendQueryString=function(){console.trace("Unsupported");}
RequestBase.prototype._timeoutError=function(reason,timeout,errno){if(this._aborted){return;}
var err=new Error(reason+timeout+'ms exceeded');err.timeout=timeout;err.code='ECONNABORTED';err.errno=errno;this.timedout=true;this.abort();this.callback(err);};RequestBase.prototype._setTimeouts=function(){var self=this;if(this._timeout&&!this._timer){this._timer=setTimeout(function(){self._timeoutError('Timeout of ',self._timeout,'ETIME');},this._timeout);}
if(this._responseTimeout&&!this._responseTimeoutTimer){this._responseTimeoutTimer=setTimeout(function(){self._timeoutError('Response timeout of ',self._responseTimeout,'ETIMEDOUT');},this._responseTimeout);}};},{"./is-object":2}],4:[function(require,module,exports){'use strict';var utils=require('./utils');module.exports=ResponseBase;function ResponseBase(obj){if(obj)return mixin(obj);}
function mixin(obj){for(var key in ResponseBase.prototype){obj[key]=ResponseBase.prototype[key];}
return obj;}
ResponseBase.prototype.get=function(field){return this.header[field.toLowerCase()];};ResponseBase.prototype._setHeaderProperties=function(header){var ct=header['content-type']||'';this.type=utils.type(ct);var params=utils.params(ct);for(var key in params)this[key]=params[key];this.links={};try{if(header.link){this.links=utils.parseLinks(header.link);}}catch(err){}};ResponseBase.prototype._setStatusProperties=function(status){var type=status/100|0;this.status=this.statusCode=status;this.statusType=type;this.info=1==type;this.ok=2==type;this.redirect=3==type;this.clientError=4==type;this.serverError=5==type;this.error=(4==type||5==type)?this.toError():false;this.created=201==status;this.accepted=202==status;this.noContent=204==status;this.badRequest=400==status;this.unauthorized=401==status;this.notAcceptable=406==status;this.forbidden=403==status;this.notFound=404==status;this.unprocessableEntity=422==status;};},{"./utils":5}],5:[function(require,module,exports){'use strict';exports.type=function(str){return str.split(/ *; */).shift();};exports.params=function(str){return str.split(/ *; */).reduce(function(obj,str){var parts=str.split(/ *= */);var key=parts.shift();var val=parts.shift();if(key&&val)obj[key]=val;return obj;},{});};exports.parseLinks=function(str){return str.split(/ *, */).reduce(function(obj,str){var parts=str.split(/ *; */);var url=parts[0].slice(1,-1);var rel=parts[1].split(/ *= */)[1].slice(1,-1);obj[rel]=url;return obj;},{});};exports.cleanHeader=function(header,changesOrigin){delete header['content-type'];delete header['content-length'];delete header['transfer-encoding'];delete header['host'];if(changesOrigin){delete header['authorization'];delete header['cookie'];}
return header;};},{}],6:[function(require,module,exports){if(typeof module!=='undefined'){module.exports=Emitter;}
function Emitter(obj){if(obj)return mixin(obj);};function mixin(obj){for(var key in Emitter.prototype){obj[key]=Emitter.prototype[key];}
return obj;}
Emitter.prototype.on=Emitter.prototype.addEventListener=function(event,fn){this._callbacks=this._callbacks||{};(this._callbacks['$'+event]=this._callbacks['$'+event]||[]).push(fn);return this;};Emitter.prototype.once=function(event,fn){function on(){this.off(event,on);fn.apply(this,arguments);}
on.fn=fn;this.on(event,on);return this;};Emitter.prototype.off=Emitter.prototype.removeListener=Emitter.prototype.removeAllListeners=Emitter.prototype.removeEventListener=function(event,fn){this._callbacks=this._callbacks||{};if(0==arguments.length){this._callbacks={};return this;}
var callbacks=this._callbacks['$'+event];if(!callbacks)return this;if(1==arguments.length){delete this._callbacks['$'+event];return this;}
var cb;for(var i=0;i<callbacks.length;i++){cb=callbacks[i];if(cb===fn||cb.fn===fn){callbacks.splice(i,1);break;}}
return this;};Emitter.prototype.emit=function(event){this._callbacks=this._callbacks||{};var args=[].slice.call(arguments,1),callbacks=this._callbacks['$'+event];if(callbacks){callbacks=callbacks.slice(0);for(var i=0,len=callbacks.length;i<len;++i){callbacks[i].apply(this,args);}}
return this;};Emitter.prototype.listeners=function(event){this._callbacks=this._callbacks||{};return this._callbacks['$'+event]||[];};Emitter.prototype.hasListeners=function(event){return!!this.listeners(event).length;};},{}],7:[function(require,module,exports){var root;if(typeof window!=='undefined'){root=window;}else if(typeof self!=='undefined'){root=self;}else{console.warn("Using browser-only version of superagent in non-browser environment");root=this;}
var Emitter=require('component-emitter');var RequestBase=require('./request-base');var isObject=require('./is-object');var ResponseBase=require('./response-base');var Agent=require('./agent-base');function noop(){};var request=exports=module.exports=function(method,url){if('function'==typeof url){return new exports.Request('GET',method).end(url);}
if(1==arguments.length){return new exports.Request('GET',method);}
return new exports.Request(method,url);}
exports.Request=Request;request.getXHR=function(){if(root.XMLHttpRequest&&(!root.location||'file:'!=root.location.protocol||!root.ActiveXObject)){return new XMLHttpRequest;}else{try{return new ActiveXObject('Microsoft.XMLHTTP');}catch(e){}
try{return new ActiveXObject('Msxml2.XMLHTTP.6.0');}catch(e){}
try{return new ActiveXObject('Msxml2.XMLHTTP.3.0');}catch(e){}
try{return new ActiveXObject('Msxml2.XMLHTTP');}catch(e){}}
throw Error("Browser-only version of superagent could not find XHR");};var trim=''.trim?function(s){return s.trim();}:function(s){return s.replace(/(^\s*|\s*$)/g,'');};function serialize(obj){if(!isObject(obj))return obj;var pairs=[];for(var key in obj){pushEncodedKeyValuePair(pairs,key,obj[key]);}
return pairs.join('&');}
function pushEncodedKeyValuePair(pairs,key,val){if(val!=null){if(Array.isArray(val)){val.forEach(function(v){pushEncodedKeyValuePair(pairs,key,v);});}else if(isObject(val)){for(var subkey in val){pushEncodedKeyValuePair(pairs,key+'['+subkey+']',val[subkey]);}}else{pairs.push(encodeURIComponent(key)
+'='+encodeURIComponent(val));}}else if(val===null){pairs.push(encodeURIComponent(key));}}
request.serializeObject=serialize;function parseString(str){var obj={};var pairs=str.split('&');var pair;var pos;for(var i=0,len=pairs.length;i<len;++i){pair=pairs[i];pos=pair.indexOf('=');if(pos==-1){obj[decodeURIComponent(pair)]='';}else{obj[decodeURIComponent(pair.slice(0,pos))]=decodeURIComponent(pair.slice(pos+1));}}
return obj;}
request.parseString=parseString;request.types={html:'text/html',json:'application/json',xml:'text/xml',urlencoded:'application/x-www-form-urlencoded','form':'application/x-www-form-urlencoded','form-data':'application/x-www-form-urlencoded'};request.serialize={'application/x-www-form-urlencoded':serialize,'application/json':JSON.stringify};request.parse={'application/x-www-form-urlencoded':parseString,'application/json':JSON.parse};function parseHeader(str){var lines=str.split(/\r?\n/);var fields={};var index;var line;var field;var val;for(var i=0,len=lines.length;i<len;++i){line=lines[i];index=line.indexOf(':');if(index===-1){continue;}
field=line.slice(0,index).toLowerCase();val=trim(line.slice(index+1));fields[field]=val;}
return fields;}
function isJSON(mime){return /[\/+]json($|[^-\w])/.test(mime);}
function Response(req){this.req=req;this.xhr=this.req.xhr;this.text=((this.req.method!='HEAD'&&(this.xhr.responseType===''||this.xhr.responseType==='text'))||typeof this.xhr.responseType==='undefined')?this.xhr.responseText:null;this.statusText=this.req.xhr.statusText;var status=this.xhr.status;if(status===1223){status=204;}
this._setStatusProperties(status);this.header=this.headers=parseHeader(this.xhr.getAllResponseHeaders());this.header['content-type']=this.xhr.getResponseHeader('content-type');this._setHeaderProperties(this.header);if(null===this.text&&req._responseType){this.body=this.xhr.response;}else{this.body=this.req.method!='HEAD'?this._parseBody(this.text?this.text:this.xhr.response):null;}}
ResponseBase(Response.prototype);Response.prototype._parseBody=function(str){var parse=request.parse[this.type];if(this.req._parser){return this.req._parser(this,str);}
if(!parse&&isJSON(this.type)){parse=request.parse['application/json'];}
return parse&&str&&(str.length||str instanceof Object)?parse(str):null;};Response.prototype.toError=function(){var req=this.req;var method=req.method;var url=req.url;var msg='cannot '+method+' '+url+' ('+this.status+')';var err=new Error(msg);err.status=this.status;err.method=method;err.url=url;return err;};request.Response=Response;function Request(method,url){var self=this;this._query=this._query||[];this.method=method;this.url=url;this.header={};this._header={};this.on('end',function(){var err=null;var res=null;try{res=new Response(self);}catch(e){err=new Error('Parser is unable to parse the response');err.parse=true;err.original=e;if(self.xhr){err.rawResponse=typeof self.xhr.responseType=='undefined'?self.xhr.responseText:self.xhr.response;err.status=self.xhr.status?self.xhr.status:null;err.statusCode=err.status;}else{err.rawResponse=null;err.status=null;}
return self.callback(err);}
self.emit('response',res);var new_err;try{if(!self._isResponseOK(res)){new_err=new Error(res.statusText||'Unsuccessful HTTP response');}}catch(custom_err){new_err=custom_err;}
if(new_err){new_err.original=err;new_err.response=res;new_err.status=res.status;self.callback(new_err,res);}else{self.callback(null,res);}});}
Emitter(Request.prototype);RequestBase(Request.prototype);Request.prototype.type=function(type){this.set('Content-Type',request.types[type]||type);return this;};Request.prototype.accept=function(type){this.set('Accept',request.types[type]||type);return this;};Request.prototype.auth=function(user,pass,options){if(1===arguments.length)pass='';if(typeof pass==='object'&&pass!==null){options=pass;pass='';}
if(!options){options={type:'function'===typeof btoa?'basic':'auto',};}
var encoder=function(string){if('function'===typeof btoa){return btoa(string);}
throw new Error('Cannot use basic auth, btoa is not a function');};return this._auth(user,pass,options,encoder);};Request.prototype.query=function(val){if('string'!=typeof val)val=serialize(val);if(val)this._query.push(val);return this;};Request.prototype.attach=function(field,file,options){if(file){if(this._data){throw Error("superagent can't mix .send() and .attach()");}
this._getFormData().append(field,file,options||file.name);}
return this;};Request.prototype._getFormData=function(){if(!this._formData){this._formData=new root.FormData();}
return this._formData;};Request.prototype.callback=function(err,res){if(this._shouldRetry(err,res)){return this._retry();}
var fn=this._callback;this.clearTimeout();if(err){if(this._maxRetries)err.retries=this._retries-1;this.emit('error',err);}
fn(err,res);};Request.prototype.crossDomainError=function(){var err=new Error('Request has been terminated\nPossible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.');err.crossDomain=true;err.status=this.status;err.method=this.method;err.url=this.url;this.callback(err);};Request.prototype.buffer=Request.prototype.ca=Request.prototype.agent=function(){console.warn("This is not supported in browser version of superagent");return this;};Request.prototype.pipe=Request.prototype.write=function(){throw Error("Streaming is not supported in browser version of superagent");};Request.prototype._isHost=function _isHost(obj){return obj&&'object'===typeof obj&&!Array.isArray(obj)&&Object.prototype.toString.call(obj)!=='[object Object]';}
Request.prototype.end=function(fn){if(this._endCalled){console.warn("Warning: .end() was called twice. This is not supported in superagent");}
this._endCalled=true;this._callback=fn||noop;this._finalizeQueryString();return this._end();};Request.prototype._end=function(){var self=this;var xhr=(this.xhr=request.getXHR());var data=this._formData||this._data;this._setTimeouts();xhr.onreadystatechange=function(){var readyState=xhr.readyState;if(readyState>=2&&self._responseTimeoutTimer){clearTimeout(self._responseTimeoutTimer);}
if(4!=readyState){return;}
var status;try{status=xhr.status}catch(e){status=0;}
if(!status){if(self.timedout||self._aborted)return;return self.crossDomainError();}
self.emit('end');};var handleProgress=function(direction,e){if(e.total>0){e.percent=e.loaded/e.total*100;}
e.direction=direction;self.emit('progress',e);};if(this.hasListeners('progress')){try{xhr.onprogress=handleProgress.bind(null,'download');if(xhr.upload){xhr.upload.onprogress=handleProgress.bind(null,'upload');}}catch(e){}}
try{if(this.username&&this.password){xhr.open(this.method,this.url,true,this.username,this.password);}else{xhr.open(this.method,this.url,true);}}catch(err){return this.callback(err);}
if(this._withCredentials)xhr.withCredentials=true;if(!this._formData&&'GET'!=this.method&&'HEAD'!=this.method&&'string'!=typeof data&&!this._isHost(data)){var contentType=this._header['content-type'];var serialize=this._serializer||request.serialize[contentType?contentType.split(';')[0]:''];if(!serialize&&isJSON(contentType)){serialize=request.serialize['application/json'];}
if(serialize)data=serialize(data);}
for(var field in this.header){if(null==this.header[field])continue;if(this.header.hasOwnProperty(field))
xhr.setRequestHeader(field,this.header[field]);}
if(this._responseType){xhr.responseType=this._responseType;}
this.emit('request',this);xhr.send(typeof data!=='undefined'?data:null);return this;};request.agent=function(){return new Agent();};["GET","POST","OPTIONS","PATCH","PUT","DELETE"].forEach(function(method){Agent.prototype[method.toLowerCase()]=function(url,fn){var req=new request.Request(method,url);this._setDefaults(req);if(fn){req.end(fn);}
return req;};});Agent.prototype.del=Agent.prototype['delete'];request.get=function(url,data,fn){var req=request('GET',url);if('function'==typeof data)(fn=data),(data=null);if(data)req.query(data);if(fn)req.end(fn);return req;};request.head=function(url,data,fn){var req=request('HEAD',url);if('function'==typeof data)(fn=data),(data=null);if(data)req.query(data);if(fn)req.end(fn);return req;};request.options=function(url,data,fn){var req=request('OPTIONS',url);if('function'==typeof data)(fn=data),(data=null);if(data)req.send(data);if(fn)req.end(fn);return req;};function del(url,data,fn){var req=request('DELETE',url);if('function'==typeof data)(fn=data),(data=null);if(data)req.send(data);if(fn)req.end(fn);return req;}
request['del']=del;request['delete']=del;request.patch=function(url,data,fn){var req=request('PATCH',url);if('function'==typeof data)(fn=data),(data=null);if(data)req.send(data);if(fn)req.end(fn);return req;};request.post=function(url,data,fn){var req=request('POST',url);if('function'==typeof data)(fn=data),(data=null);if(data)req.send(data);if(fn)req.end(fn);return req;};request.put=function(url,data,fn){var req=request('PUT',url);if('function'==typeof data)(fn=data),(data=null);if(data)req.send(data);if(fn)req.end(fn);return req;};},{"./agent-base":1,"./is-object":2,"./request-base":3,"./response-base":4,"component-emitter":6}]},{},[7])(7)});